# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luis/workspace/Cudg3d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luis/workspace/Cudg3d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luis/workspace/Cudg3d/CMakeFiles /home/luis/workspace/Cudg3d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luis/workspace/Cudg3d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gidpost

# Build rule for target.
gidpost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gidpost
.PHONY : gidpost

# fast build rule for target.
gidpost/fast:
	$(MAKE) -f opensemba/obj/external/gidpost/CMakeFiles/gidpost.dir/build.make opensemba/obj/external/gidpost/CMakeFiles/gidpost.dir/build
.PHONY : gidpost/fast

#=============================================================================
# Target rules for targets named opensemba_core_data

# Build rule for target.
opensemba_core_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_data
.PHONY : opensemba_core_data

# fast build rule for target.
opensemba_core_data/fast:
	$(MAKE) -f opensemba/obj/src/core/CMakeFiles/opensemba_core_data.dir/build.make opensemba/obj/src/core/CMakeFiles/opensemba_core_data.dir/build
.PHONY : opensemba_core_data/fast

#=============================================================================
# Target rules for targets named opensemba_core_solver

# Build rule for target.
opensemba_core_solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_solver
.PHONY : opensemba_core_solver

# fast build rule for target.
opensemba_core_solver/fast:
	$(MAKE) -f opensemba/obj/src/core/solver/CMakeFiles/opensemba_core_solver.dir/build.make opensemba/obj/src/core/solver/CMakeFiles/opensemba_core_solver.dir/build
.PHONY : opensemba_core_solver/fast

#=============================================================================
# Target rules for targets named opensemba_core_group

# Build rule for target.
opensemba_core_group: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_group
.PHONY : opensemba_core_group

# fast build rule for target.
opensemba_core_group/fast:
	$(MAKE) -f opensemba/obj/src/core/group/CMakeFiles/opensemba_core_group.dir/build.make opensemba/obj/src/core/group/CMakeFiles/opensemba_core_group.dir/build
.PHONY : opensemba_core_group/fast

#=============================================================================
# Target rules for targets named opensemba_core_physicalmodel

# Build rule for target.
opensemba_core_physicalmodel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_physicalmodel
.PHONY : opensemba_core_physicalmodel

# fast build rule for target.
opensemba_core_physicalmodel/fast:
	$(MAKE) -f opensemba/obj/src/core/physicalModel/CMakeFiles/opensemba_core_physicalmodel.dir/build.make opensemba/obj/src/core/physicalModel/CMakeFiles/opensemba_core_physicalmodel.dir/build
.PHONY : opensemba_core_physicalmodel/fast

#=============================================================================
# Target rules for targets named opensemba_core_argument

# Build rule for target.
opensemba_core_argument: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_argument
.PHONY : opensemba_core_argument

# fast build rule for target.
opensemba_core_argument/fast:
	$(MAKE) -f opensemba/obj/src/core/argument/CMakeFiles/opensemba_core_argument.dir/build.make opensemba/obj/src/core/argument/CMakeFiles/opensemba_core_argument.dir/build
.PHONY : opensemba_core_argument/fast

#=============================================================================
# Target rules for targets named opensemba_core_parser

# Build rule for target.
opensemba_core_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_parser
.PHONY : opensemba_core_parser

# fast build rule for target.
opensemba_core_parser/fast:
	$(MAKE) -f opensemba/obj/src/core/parser/CMakeFiles/opensemba_core_parser.dir/build.make opensemba/obj/src/core/parser/CMakeFiles/opensemba_core_parser.dir/build
.PHONY : opensemba_core_parser/fast

#=============================================================================
# Target rules for targets named opensemba_core_math

# Build rule for target.
opensemba_core_math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_math
.PHONY : opensemba_core_math

# fast build rule for target.
opensemba_core_math/fast:
	$(MAKE) -f opensemba/obj/src/core/math/CMakeFiles/opensemba_core_math.dir/build.make opensemba/obj/src/core/math/CMakeFiles/opensemba_core_math.dir/build
.PHONY : opensemba_core_math/fast

#=============================================================================
# Target rules for targets named opensemba_core_class

# Build rule for target.
opensemba_core_class: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_class
.PHONY : opensemba_core_class

# fast build rule for target.
opensemba_core_class/fast:
	$(MAKE) -f opensemba/obj/src/core/class/CMakeFiles/opensemba_core_class.dir/build.make opensemba/obj/src/core/class/CMakeFiles/opensemba_core_class.dir/build
.PHONY : opensemba_core_class/fast

#=============================================================================
# Target rules for targets named opensemba_core_geometry

# Build rule for target.
opensemba_core_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_geometry
.PHONY : opensemba_core_geometry

# fast build rule for target.
opensemba_core_geometry/fast:
	$(MAKE) -f opensemba/obj/src/core/geometry/CMakeFiles/opensemba_core_geometry.dir/build.make opensemba/obj/src/core/geometry/CMakeFiles/opensemba_core_geometry.dir/build
.PHONY : opensemba_core_geometry/fast

#=============================================================================
# Target rules for targets named opensemba_core_filesystem

# Build rule for target.
opensemba_core_filesystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_filesystem
.PHONY : opensemba_core_filesystem

# fast build rule for target.
opensemba_core_filesystem/fast:
	$(MAKE) -f opensemba/obj/src/core/filesystem/CMakeFiles/opensemba_core_filesystem.dir/build.make opensemba/obj/src/core/filesystem/CMakeFiles/opensemba_core_filesystem.dir/build
.PHONY : opensemba_core_filesystem/fast

#=============================================================================
# Target rules for targets named opensemba_core_source

# Build rule for target.
opensemba_core_source: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_source
.PHONY : opensemba_core_source

# fast build rule for target.
opensemba_core_source/fast:
	$(MAKE) -f opensemba/obj/src/core/source/CMakeFiles/opensemba_core_source.dir/build.make opensemba/obj/src/core/source/CMakeFiles/opensemba_core_source.dir/build
.PHONY : opensemba_core_source/fast

#=============================================================================
# Target rules for targets named opensemba_core_outputrequest

# Build rule for target.
opensemba_core_outputrequest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_outputrequest
.PHONY : opensemba_core_outputrequest

# fast build rule for target.
opensemba_core_outputrequest/fast:
	$(MAKE) -f opensemba/obj/src/core/outputRequest/CMakeFiles/opensemba_core_outputrequest.dir/build.make opensemba/obj/src/core/outputRequest/CMakeFiles/opensemba_core_outputrequest.dir/build
.PHONY : opensemba_core_outputrequest/fast

#=============================================================================
# Target rules for targets named opensemba_core_exporter

# Build rule for target.
opensemba_core_exporter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_exporter
.PHONY : opensemba_core_exporter

# fast build rule for target.
opensemba_core_exporter/fast:
	$(MAKE) -f opensemba/obj/src/core/exporter/CMakeFiles/opensemba_core_exporter.dir/build.make opensemba/obj/src/core/exporter/CMakeFiles/opensemba_core_exporter.dir/build
.PHONY : opensemba_core_exporter/fast

#=============================================================================
# Target rules for targets named opensemba_core_util

# Build rule for target.
opensemba_core_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_core_util
.PHONY : opensemba_core_util

# fast build rule for target.
opensemba_core_util/fast:
	$(MAKE) -f opensemba/obj/src/core/util/CMakeFiles/opensemba_core_util.dir/build.make opensemba/obj/src/core/util/CMakeFiles/opensemba_core_util.dir/build
.PHONY : opensemba_core_util/fast

#=============================================================================
# Target rules for targets named opensemba_parser_gid

# Build rule for target.
opensemba_parser_gid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_parser_gid
.PHONY : opensemba_parser_gid

# fast build rule for target.
opensemba_parser_gid/fast:
	$(MAKE) -f opensemba/obj/src/parser/gid/CMakeFiles/opensemba_parser_gid.dir/build.make opensemba/obj/src/parser/gid/CMakeFiles/opensemba_parser_gid.dir/build
.PHONY : opensemba_parser_gid/fast

#=============================================================================
# Target rules for targets named opensemba_parser_stl

# Build rule for target.
opensemba_parser_stl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_parser_stl
.PHONY : opensemba_parser_stl

# fast build rule for target.
opensemba_parser_stl/fast:
	$(MAKE) -f opensemba/obj/src/parser/stl/CMakeFiles/opensemba_parser_stl.dir/build.make opensemba/obj/src/parser/stl/CMakeFiles/opensemba_parser_stl.dir/build
.PHONY : opensemba_parser_stl/fast

#=============================================================================
# Target rules for targets named opensemba_mesher

# Build rule for target.
opensemba_mesher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_mesher
.PHONY : opensemba_mesher

# fast build rule for target.
opensemba_mesher/fast:
	$(MAKE) -f opensemba/obj/src/mesher/CMakeFiles/opensemba_mesher.dir/build.make opensemba/obj/src/mesher/CMakeFiles/opensemba_mesher.dir/build
.PHONY : opensemba_mesher/fast

#=============================================================================
# Target rules for targets named opensemba_exporter_vtk

# Build rule for target.
opensemba_exporter_vtk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_exporter_vtk
.PHONY : opensemba_exporter_vtk

# fast build rule for target.
opensemba_exporter_vtk/fast:
	$(MAKE) -f opensemba/obj/src/exporter/vtk/CMakeFiles/opensemba_exporter_vtk.dir/build.make opensemba/obj/src/exporter/vtk/CMakeFiles/opensemba_exporter_vtk.dir/build
.PHONY : opensemba_exporter_vtk/fast

#=============================================================================
# Target rules for targets named opensemba_exporter_gid

# Build rule for target.
opensemba_exporter_gid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_exporter_gid
.PHONY : opensemba_exporter_gid

# fast build rule for target.
opensemba_exporter_gid/fast:
	$(MAKE) -f opensemba/obj/src/exporter/gid/CMakeFiles/opensemba_exporter_gid.dir/build.make opensemba/obj/src/exporter/gid/CMakeFiles/opensemba_exporter_gid.dir/build
.PHONY : opensemba_exporter_gid/fast

#=============================================================================
# Target rules for targets named opensemba_solver

# Build rule for target.
opensemba_solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_solver
.PHONY : opensemba_solver

# fast build rule for target.
opensemba_solver/fast:
	$(MAKE) -f opensemba/obj/src/solver/CMakeFiles/opensemba_solver.dir/build.make opensemba/obj/src/solver/CMakeFiles/opensemba_solver.dir/build
.PHONY : opensemba_solver/fast

#=============================================================================
# Target rules for targets named opensemba_test

# Build rule for target.
opensemba_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensemba_test
.PHONY : opensemba_test

# fast build rule for target.
opensemba_test/fast:
	$(MAKE) -f opensemba/obj/src/apps/test/CMakeFiles/opensemba_test.dir/build.make opensemba/obj/src/apps/test/CMakeFiles/opensemba_test.dir/build
.PHONY : opensemba_test/fast

#=============================================================================
# Target rules for targets named cudg3d

# Build rule for target.
cudg3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudg3d
.PHONY : cudg3d

# fast build rule for target.
cudg3d/fast:
	$(MAKE) -f src/apps/cudg3d/CMakeFiles/cudg3d.dir/build.make src/apps/cudg3d/CMakeFiles/cudg3d.dir/build
.PHONY : cudg3d/fast

#=============================================================================
# Target rules for targets named cudg3d_core

# Build rule for target.
cudg3d_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudg3d_core
.PHONY : cudg3d_core

# fast build rule for target.
cudg3d_core/fast:
	$(MAKE) -f src/apps/cudg3d/core/CMakeFiles/cudg3d_core.dir/build.make src/apps/cudg3d/core/CMakeFiles/cudg3d_core.dir/build
.PHONY : cudg3d_core/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gidpost"
	@echo "... opensemba_core_data"
	@echo "... opensemba_core_solver"
	@echo "... opensemba_core_group"
	@echo "... opensemba_core_physicalmodel"
	@echo "... opensemba_core_argument"
	@echo "... opensemba_core_parser"
	@echo "... opensemba_core_math"
	@echo "... opensemba_core_class"
	@echo "... opensemba_core_geometry"
	@echo "... opensemba_core_filesystem"
	@echo "... opensemba_core_source"
	@echo "... opensemba_core_outputrequest"
	@echo "... opensemba_core_exporter"
	@echo "... opensemba_core_util"
	@echo "... opensemba_parser_gid"
	@echo "... opensemba_parser_stl"
	@echo "... opensemba_mesher"
	@echo "... opensemba_exporter_vtk"
	@echo "... opensemba_exporter_gid"
	@echo "... opensemba_solver"
	@echo "... opensemba_test"
	@echo "... cudg3d"
	@echo "... cudg3d_core"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

