name: ubuntu-gnu

on:    
  pull_request:
    branches:
      - main
      - dev

jobs:
  
  builds-and-test:
    runs-on: ubuntu-latest
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    # 1. Install MPI on the Ubuntu runner
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    # 2. Build and Export METIS
    - name: Build METIS
      run: |
        git clone https://github.com/mfem/ThirdParty-metis-5.1.0.git metis
        cd metis
        make config shared=1 prefix=$GITHUB_WORKSPACE/metis/install
        make install -j $(nproc)
        echo "METIS_DIR=$GITHUB_WORKSPACE/metis/install" >> $GITHUB_ENV

    # 3. Build and Export HYPRE
    - name: Build HYPRE
      run: |
        git clone --depth 1 https://github.com/hypre-space/hypre.git
        cd hypre/src
        ./configure --disable-fortran --prefix=$GITHUB_WORKSPACE/hypre/install
        make install -j $(nproc)
        echo "HYPRE_DIR=$GITHUB_WORKSPACE/hypre/install" >> $GITHUB_ENV

    # - name: Builds mfem-geg
    #   run: | 
    #     cmake -S external/mfem-geg \
    #           -B mfem-geg-build/ \
    #           -DCMAKE_BUILD_TYPE=Release \
    #           -DCMAKE_INSTALL_PREFIX=mfem-geg-install \
    #           -G Ninja
    #     cmake --build mfem-geg-build/ -j
    #     cmake --install mfem-geg-build/

    # 4. Swap to the MPI presets
    - name: Builds semba/dgtd
      uses: lukka/run-cmake@v10
      # lukka/run-cmake will automatically pick up METIS_DIR and HYPRE_DIR from $GITHUB_ENV
      with:
        configurePreset: 'gnu-release-mpi'
        buildPreset: 'build-gnu-release-mpi'
        buildPresetAdditionalArgs: "['--parallel']"

    # 5. Update paths and run with mpiexec (using 2 cores)
    - name: Run hesthavenComparison tests 
      run: mpiexec -n 2 build/gnu-release-mpi/bin/hesthavenComparison_tests

    - name: Run mfem tests 
      run: mpiexec -n 2 build/gnu-release-mpi/bin/mfem_tests

    - name: Run maxwell tests 
      run: mpiexec -n 2 build/gnu-release-mpi/bin/maxwell_tests

    - name: Run maxwell solver tests
      run: mpiexec -n 2 build/gnu-release-mpi/bin/maxwell_solver_tests

    - name: Run maxwell cases tests
      run: mpiexec -n 2 build/gnu-release-mpi/bin/cases_tests

    # - name: Run system tests 
    #   run: |
    #     mpiexec -n 2 build/gnu-release-mpi/bin/rcs_tests